apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-service-account
  namespace: hackathon-devops

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: devops-service-account
  namespace: hackathon-devops
roleRef:
  kind: ClusterRole
  name: devops-cluster-role
  apiGroup: rbac.authorization.k8s.io
